### PR TITLE
Small API expansion & docs

### PR DESCRIPTION
**Pull request by John-Toohey**
Hello! This is the exact same as  #25, except I fixed the documentation/tests.

### CODE REVIEW

**Comment by devashishdxt** [comment]
Hi. Thanks for creating this PR. I haven't reviewed the changes in detail, but on the surface, they look good. Can you mark this as `Ready for review`?

**Comment by greenfierydragon** [comment]
Note I didn't manage a 'getAllKeys' function because, to be frank, I underestimated the complexity of the IndexedDB Api.

**Comment by istankovic** [comment]
@devashishdxt could you please look into this and see if it can be merged?
We have a fork of this in [Wire](https://github.com/wireapp) and would like to get rid of it and go back to track the upstream closely, but we need this.

**Comment by devashishdxt** [comment]
> @devashishdxt could you please look into this and see if it can be merged? We have a fork of this in [Wire](https://github.com/wireapp) and would like to get rid of it and go back to track the upstream closely, but we need this.

Sure. I'll take a look over the weekend.

**Review by devashishdxt — APPROVED** [review]

**Comment by istankovic** [comment]
Thank you so much, that was really quick! :purple_heart:

**Pull request merged**
